### ISSUE TITLE
Phosphor causes crash on startup

### ISSUE THREAD

**Issue by Gavin456b** [jellysquid3/phosphor-forge#66]
I went through all my mods and disabling phosphor fixes the issue. This crash is only caused by the latest version of Phosphor. I am on 1.12.2
Here is my crash log

java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.util.ServiceConfigurationError: org.spongepowered.asm.service.IMixinServiceBootstrap: Provider org.spongepowered.asm.service.modlauncher.MixinServiceModLauncherBootstrap could not be instantiated
	at java.util.ServiceLoader.fail(ServiceLoader.java:232)
	at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
	at java.util.ServiceLoader$LazyIterator.access$700(ServiceLoader.java:323)
	at java.util.ServiceLoader$LazyIterator$2.run(ServiceLoader.java:407)
	at java.security.AccessController.doPrivileged(AccessController.java:704)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:409)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at org.spongepowered.asm.service.MixinService.runBootServices(MixinService.java:77)
	at org.spongepowered.asm.service.MixinService.<init>(MixinService.java:72)
	at org.spongepowered.asm.service.MixinService.getInstance(MixinService.java:92)
	at org.spongepowered.asm.service.MixinService.boot(MixinService.java:102)
	at org.spongepowered.asm.launch.MixinBootstrap.<clinit>(MixinBootstrap.java:76)
	at org.spongepowered.asm.launch.MixinTweaker.<init>(MixinTweaker.java:44)
	at java.lang.J9VMInternals.newInstanceImpl(Native Method)
	at java.lang.Class.newInstance(Class.java:1852)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	... 8 more
Caused by: java.lang.SecurityException: Signers of 'org.spongepowered.asm.service.ServiceInitialisationException' do not match signers of other classes in package
	at java.lang.ClassLoader.checkPackageSigners(ClassLoader.java:461)
	at java.lang.ClassLoader.defineClassInternal(ClassLoader.java:385)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:359)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:682)
	at java.net.URLClassLoader.access$400(URLClassLoader.java:89)
	at java.net.URLClassLoader$ClassFinder.run(URLClassLoader.java:1086)
	at java.security.AccessController.doPrivileged(AccessController.java:770)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:589)
	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:953)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:898)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:881)
	at java.lang.J9VMInternals.newInstanceImpl(Native Method)
	at java.lang.Class.newInstance(Class.java:1852)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
	... 23 more
Exception in thread "main" net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
	at java.lang.Runtime.exit(Runtime.java:108)
	at java.lang.System.exit(System.java:345)
	at org.multimc.EntryPoint.main(EntryPoint.java:38)
[09:45:13] [main/INFO] [STDOUT]: [org.multimc.EntryPoint:main:37]: Exiting with -1
Process exited with code 1.

**Comment by jellysquid3** [comment]
Phosphor for Minecraft 1.12 is no longer supported and will not receive additional updates outside of those for maintenance sake.
