### ISSUE TITLE
Crash when launching the last version of Phosphor

### ISSUE THREAD

**Issue by LuuNyX** [jellysquid3/phosphor-forge#69]
Hello, I've a problem, when I try to launch my game with phosphor, it crash instantly...

``[14:40:01] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from phosphor-forge-mc1.12.2-0.2.7-universal.jar
[14:40:01] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[14:40:01] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[14:40:01] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: java.util.ServiceConfigurationError: org.spongepowered.asm.service.IMixinServiceBootstrap: Provider org.spongepowered.asm.service.modlauncher.MixinServiceModLauncherBootstrap could not be instantiated
[14:40:01] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.ServiceLoader.fail(ServiceLoader.java:232)
[14:40:01] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
[14:40:01] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
[14:40:01] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.ServiceLoader$LazyIterator.access$700(ServiceLoader.java:323)
[14:40:01] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.ServiceLoader$LazyIterator$2.run(ServiceLoader.java:407)
[14:40:01] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.security.AccessController.doPrivileged(Native Method)
[14:40:01] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:409)
[14:40:01] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
[14:40:01] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.service.MixinService.runBootServices(MixinService.java:77)
[14:40:01] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.service.MixinService.<init>(MixinService.java:72)
[14:40:01] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.service.MixinService.getInstance(MixinService.java:92)
[14:40:01] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.service.MixinService.boot(MixinService.java:102)
[14:40:01] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.MixinBootstrap.<clinit>(MixinBootstrap.java:76)
[14:40:01] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.MixinTweaker.<init>(MixinTweaker.java:44)
[14:40:01] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[14:40:01] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[14:40:01] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[14:40:01] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
[14:40:01] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Class.newInstance(Class.java:442)
[14:40:01] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98)
[14:40:01] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[14:40:01] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: Caused by: java.lang.SecurityException: class "org.spongepowered.asm.service.ServiceInitialisationException"'s signer information does not match signer information of other classes in the same package
[14:40:01] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.ClassLoader.checkCerts(ClassLoader.java:895)
[14:40:01] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.ClassLoader.preDefineClass(ClassLoader.java:665)
[14:40:01] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.ClassLoader.defineClass(ClassLoader.java:758)
[14:40:01] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[14:40:01] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
[14:40:01] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
[14:40:01] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
[14:40:01] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
[14:40:01] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.security.AccessController.doPrivileged(Native Method)
[14:40:01] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
[14:40:01] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[14:40:01] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
[14:40:01] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[14:40:01] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.Class.getDeclaredConstructors0(Native Method)
[14:40:01] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
[14:40:01] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.Class.getConstructor0(Class.java:3075)
[14:40:01] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.Class.newInstance(Class.java:412)
[14:40:01] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
[14:40:01] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	... 18 more``

(There is just the phosphor part, not the rest)

**Comment by jellysquid3** [comment]
Per the information panel for Phosphor 0.2.7:
> You do not want to use this release unless you have specific mods which require Mixins 0.8.
Use Phosphor 0.2.6.
